stages:
    data_prep:
        cmd: python source/data_prep.py --config parameters.yaml
        deps:
        - source/data_prep.py
        outs:
        - data/processed
    train:
        cmd: python source/train.py --config parameters.yaml
        deps:
        - source/train.py
        - data/LJSpeech-1.1/
        outs:
        - models/